name: Deploy via AWS SSM

on:
  push:
    branches:
      - main

permissions:
  id-token: write         # Required for OIDC
  contents: read          # Required to checkout the code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy via AWS SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy App" \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --parameters '{"commands":["sudo -u ubuntu bash -c \"cd /home/ubuntu/MKC1 && export PATH=\\$HOME/.nvm/versions/node/v22.17.1/bin:\\$PATH && git pull org main && npm install && pm2 restart 0\""]}' \
            --timeout-seconds 600 \
            --region ${{ secrets.AWS_REGION }}


